package fr.gpmsi.hapi;

/**
 * Description pour chaque balise XML importante.
 * Informations tirées de IHE_FRANCE_PAM_National_Extension_v2.10.5
 */
class Ihe2_10TagDescriptions {
  static HashMap<String, String> descriptionsByTag = [
    'MSH': 'Message Header',
    'MSH.1': '/Field Separator',
    'MSH.2': '/Encoding Characters',
    'MSH.3': 'Sending Application',
    'MSH.4': 'Sending Facility',
    'MSH.5': 'Receiving Application',
    'MSH.6': 'Receiving Facility',
    'MSH.7': 'Date/Time Of Message',
    'MSH.8': '/Security',
    'MSH.9': 'Message Type',
    'MSH.10': '/Message Control ID',
    'MSH.11': '/Processing ID',
    'MSH.12': '/Version ID',
    'MSH.13': '/Sequence Number',
    'MSH.14': '/Continuation Pointer',
    'MSH.15': '/Accept Acknowledgment Type',
    'MSH.16': '/Application Acknowledgment Type',
    'MSH.17': '/Country Code',
    'MSH.18': '/Character Set',
    'MSH.19': 'Principal Language Of Message',
    'MSH.20': '/Alternate Character Set Handling Scheme',
    'MSH.21': 'Message Profile Identifier',
    'EVN': 'Event Type',
    'EVN.1': 'Event Type Code',
    'EVN.2': 'Recorded Date/Time',
    'EVN.3': 'Date/Time Planned Event',
    'EVN.4': '/Event Reason Code',
    'EVN.5': 'Operator ID',
    'EVN.6': 'Event Occurred',
    'EVN.7': 'Event Facility',
    'PID': 'Patient Identification',    
    'PID.2': 'Patient ID',
    'PID.3' : 'Liste des identifiants du patient (CX, répétable) ',
    'PID.4' : 'Alternate Patient ID - PID',
    'PID.5' : 'Nom du patient (XPN, répétable) ',
    'PID.6' : 'Nom de naissance de la mère (XPN) ',
    'PID.7' : 'Date de naissance (TS) ',
    'PID.8' : '/Sexe du patient (IS) ',
    'PID.9' : 'Patient Alias',
    'PID.10' : 'Race',
    'PID.11' : 'Adresse du patient (XAD) ',
    'PID.12' : 'County Code',
    'PID.13' : 'Phone Number - Home',
    'PID.14' : 'Phone Number - Business',
    'PID.15' : 'Langue principale (CE) ',
    'PID.16' : 'Situation de famille (CE) ',
    'PID.17' : 'Religion',
    'PID.18' : 'Numéro de Dossier Administratif (CX) ',
    'PID.19' : 'SSN Number – Patient ',
    'PID.20' : 'Driver\'s License Number - Patient',
    'PID.21' : 'Lien Mère Enfant ',
    'PID.22' : 'Ethnic Group',
    'PID.23' : 'Birth Place',
    'PID.24' : 'Multiple Birth Indicator',
    'PID.25' : 'Rang gémellaire (NM) ',
    'PID.26' : 'Citoyenneté (CE, répétable) ',
    'PID.27' : 'Veterans Military Status',
    'PID.28' : 'Nationalité (CE) ',
    'PID.29' : 'Patient Death Date and Time',
    'PID.30' : '/Patient Death Indicator',
    'PID.31' : '/Identity Unknown Indicator',
    'PID.32' : '/Statut de l’identité (IS) ',
    'PID.33' : 'Last Update Date/Time',
    'PID.34' : 'Entité modificatrice de l’identité (HD) ',
    'PID.35' : 'Species Code',
    'PID.36' : 'Breed Code',
    'PID.37' : 'Strain',
    'PID.38' : 'Production Class Code',
    'PID.39' : 'Tribal Citizenship',
    'PD': 'Additional Demographics',
    'PD1.2' : '/Mode de vie (IS) ',
    'PD1.3' : '',
    'PD1.4' : '',
    'PD1.5' : '',
    'PD1.6' : '',
    'PD1.7' : '',
    'PD1.8' : '',
    'PD1.9' : '',
    'PD1.10' : '',
    'PD1.11' : '',
    'PD1.12' : '/Protection des données du patient ',
    'ROL': 'Role',
    'ROL.2' : 'Code de l’action (ID) ',
    'ROL.3' : 'Nature du rôle (CE) ',
    'ROL.4' : 'Personne dans le rôle (XCN) ',
    'ROL.5' : 'Date de prise d’effet du rôle (TS) ',
    'ROL.6' : 'Date de fin d’effet du rôle (TS) ',
    'ROL.7' : 'Role Duration',
    'ROL.8' : 'Role Action Reason',
    'ROL.9' : 'Provider Type',
    'ROL.10' : 'Organization Unit Type',
    'ROL.11' : 'Office/Home Address/Birthplace',
    'ROL.12' : 'Phone',
    'NK1': 'Next of Kin / Associated Parties',
    'NK1.2' : 'Name',
    'NK1.3' : 'Nature de la relation *',
    'NK1.4' : 'Address',
    'NK1.5' : 'Phone Number',
    'NK1.5' : 'Business Phone Number',
    'NK1.7' : 'Rôle de la personne *',
    'NK1.8' : 'Start Date',
    'NK1.9' : 'End Date',
    'NK1.10' : 'Next of Kin / Associated Parties Job Title',
    'NK1.11' : 'Next of Kin / Associated Parties Job Code/Class',
    'NK1.12' : 'Next of Kin / Associated Parties Employee Number',
    'NK1.13' : 'Organization Name - NK1',
    'NK1.14' : 'Marital Status',
    'NK1.15' : 'Administrative Sex',
    'NK1.16' : 'Date/Time of Birth',
    'NK1.17' : 'Living Dependency',
    'NK1.18' : 'Ambulatory Status',
    'NK1.19' : 'Citizenship',
    'NK1.20' : 'Primary Language',
    'NK1.21' : 'Living Arrangement',
    'NK1.22' : 'Publicity Code',
    'NK1.23' : 'Protection Indicator',
    'NK1.24' : 'Student Indicator',
    'NK1.25' : 'Religion',
    'NK1.26' : 'Mother’s Maiden Name',
    'NK1.27' : 'Nationality',
    'NK1.28' : 'Ethnic Group',
    'NK1.29' : 'Contact Reason',
    'NK1.30' : 'Contact Person’s Name',
    'NK1.31' : 'Contact Person’s Telephone Number',
    'NK1.32' : 'Contact Person’s Address',
    'NK1.33' : 'Liste des identifiants de la personne à prévenir ou de la personne de confiance *',
    'NK1.34' : 'Job Status',
    'NK1.35' : 'Race',
    'NK1.36' : 'Handicap',
    'NK1.37' : 'Contact Person Social Security Number',
    'NK1.38' : 'Next of Kin Birth Place',
    'NK1.39' : '/VIP Indicator',
    'PV1': 'Patient Visit',
    'PV1.2' : '/Classe de patient (IS) ',
    'PV1.3' : 'Hébergement du patient (PL) ',
    'PV1.4' : '/Type d’admission (IS) ',
    'PV1.5' : 'Preadmit Number (CX) ',
    'PV1.6' : 'Prior Patient Location',
    'PV1.7' : 'Médecin responsable (XCN) ',
    'PV1.8' : 'Médecin adressant (XCN) ',
    'PV1.9' : 'Consulting Doctor',
    'PV1.10' : '/Discipline médico-tarifaire (IS) ',
    'PV1.11' : 'Temporary Location',
    'PV1.12' : 'Preadmit Test Indicator',
    'PV1.13' : 'Re-admission Indicator',
    'PV1.14' : '/Mode d’entrée personnalisé (IS) ',
    'PV1.15' : 'Ambulatory Status',
    'PV1.16' : '/Indicateur VIP ',
    'PV1.17' : 'Médecin ayant admis le patient (XCN) ',
    'PV1.18' : 'Patient Type',
    'PV1.19' : 'Identifiant de la venue (CX) ',
    'PV1.20' : 'Code tarif du mouvement (FC) ',
    'PV1.21' : '/Type d’activité, mode de traitement (IS) ',
    'PV1.22' : '/Demande de chambre particulière ',
    'PV1.23' : 'Credit Rating',
    'PV1.24' : 'Contract Code',
    'PV1.25' : 'Contract Effective Date',
    'PV1.26' : 'Contract Amount',
    'PV1.27' : 'Contract Period',
    'PV1.28' : 'Interest Code',
    'PV1.29' : 'Transfer to Bad Debt Code',
    'PV1.30' : 'Transfer to Bad Debt Date',
    'PV1.31' : 'Bad Debt Agency Code',
    'PV1.32' : 'Bad Debt Transfer Amount',
    'PV1.33' : 'Bad Debt Recovery Amount',
    'PV1.34' : 'Delete Account Indicator',
    'PV1.35' : 'Delete Account Date',
    'PV1.36' : '/Circonstance de sortie (IS) ',
    'PV1.37' : 'Etablissement de destination (DLD) ',
    'PV1.38' : 'Diet Type',
    'PV1.39' : 'Servicing Facility',
    'PV1.40' : 'Statut du lit (champ interdit) ',
    'PV1.41' : '/Statut du dossier administratif (IS) ',
    'PV1.42' : 'Pending Location',
    'PV1.43' : 'Prior Temporary Location',
    'PV1.44' : 'Admit Date/Time',
    'PV1.45' : 'Discharge Date/Time',
    'PV1.46' : 'Current Patient Balance',
    'PV1.47' : 'Total Charges',
    'PV1.48' : 'Total Adjustments',
    'PV1.49' : 'Total Payments',
    'PV1.50' : 'Alternate Visit ID',
    'PV1.51' : 'Visit Indicator',
    'PV1.52' : 'Other Healthcare Provider',
    'PV2': 'Patient Visit – Additional Info',
    'PV2.2' : 'Gestion de l’utilisation de la chambre ',
    'PV2.3' : 'Mode de placement en psychiatrie (CE), obsolète (cf. ZFS.6) ',
    'PV2.4' : 'Transfer Reason',
    'PV2.5' : 'Patient Valuables',
    'PV2.6' : 'Patient Valuables Location',
    'PV2.7' : '/Indicateur de parcours de soins coordonné (IS) ',
    'PV2.8' : 'Date d’entrée prévisionnelle (TS) ',
    'PV2.9' : 'Date de sortie prévisionnelle (TS) ',
    'PV2.10' : 'Estimated Length of Inpatient Stay',
    'PV2.11' : 'Actual Length of Inpatient Stay',
    'PV2.12' : 'Commentaire sur l’admission (ST) ',
    'PV2.13' : 'Referral Source Code',
    'PV2.14' : 'Previous Service Date',
    'PV2.15' : 'Employment Illness Related Indicator',
    'PV2.16' : 'Purge Status Code',
    'PV2.17' : 'Purge Status Date',
    'PV2.18' : '/Indication sur les conditions de prise en charge du patient (IS) ',
    'PV2.19' : 'Retention Indicator',
    'PV2.20' : 'Expected Number of Insurance Plans',
    'PV2.21' : 'Visit Publicity Code',
    'PV2.22' : '/Protection concernant la venue (ID) ',
    'PV2.23' : 'Clinic Organization Name',
    'PV2.24' : 'Patient Status Code',
    'PV2.25' : 'Visit Priority Code',
    'PV2.26' : 'Previous Treatment Date',
    'PV2.27' : 'Expected Discharge Disposition',
    'PV2.28' : 'Signature on File Date',
    'PV2.29' : 'First Similar Illness Date',
    'PV2.30' : 'Ajustement des charges du patient ',
    'PV2.31' : 'Recurring Service Code',
    'PV2.32' : 'Billing Media Code',
    'PV2.33' : 'Expected Surgery Date and Time',
    'PV2.34' : 'Military Partnership Code',
    'PV2.35' : 'Military Non-Availability Code',
    'PV2.36' : 'Newborn Baby Indicator',
    'PV2.37' : 'Baby Detained Indicator',
    'PV2.38' : 'Mode de transport d’entrée (CE) ',
    'PV2.39' : 'Recreational Drug Use Code',
    'PV2.40' : 'Admission Level of Care Code',
    'PV2.41' : 'Precaution Code',
    'PV2.42' : 'Patient Condition Code',
    'PV2.43' : 'Living Will Code',
    'PV2.44' : 'Organ Donor Code',
    'PV2.45' : 'Advance Directive Code',
    'PV2.46' : 'Patient Status Effective Date',
    'PV2.47' : 'Date prévue de retour de permission (TS) ',
    'PV2.48' : 'Expected Pre-admission Testing Date/Time',
    'PV2.49' : 'Notify Clergy Code',
    'ACC.1' : 'Date de l’accident (TS) ',
    'ACC.2' : 'Nature de l’accident (CE) ',
    'ACC.3' : 'Accident Location',
    'ACC.4' : 'Auto Accident State',
    'ACC.5' : 'Accident Job Related Indicator',
    'ACC.6' : 'Accident Death Indicator',
    'ACC.7' : 'Entered By',
    'ACC.8' : 'Accident Description',
    'ACC.9' : 'Brought In By',
    'ACC.10' : 'Police Notified Indicator',
    'ACC.11' : 'Accident Address',
    'ZBE': 'Movement segment',
    'ZBE.1' : 'Identifiant du mouvement (EI) ',
    'ZBE.2' : 'Date et heure de création du mouvement (TS) ',
    'ZBE.3' : 'Borne de fin de la période initiée par le mouvement (TS) ',
    'ZBE.4' : '/Code action portant sur le mouvement (ID) ',
    'ZBE.5' : '/Indicateur de mouvement historique (ID) ',
    'ZBE.6' : 'Code d’événement d’origine (ID) ',
    'ZBE.7' : 'UF de responsabilité médicale (XON) ',
    'ZBE.8' : 'UF de responsabilité des soins (XON) ',
    'ZBE.9' : 'Nature du mouvement (CWE) ',
    'ZFA': 'Statut DMP',
    'ZFA.1' : 'Statut du DMP du patient (ID) ',
    'ZFA.2' : 'Date de recueil du statut du DMP du patient (TS) ',
    'ZFA.3' : 'Date de fermeture du DMP du patient (TS) ',
    'ZFA.4' : 'Autorisation valide d’accès au DMP du patient pour l’établissement (ID) ',
    'ZFA.5' : 'Date de recueil de l’état de l’autorisation d’accès au DMP du patient pour l’établissement (TS) ',
    'ZFA.6' : 'Opposition du patient à l’accès en mode bris de glace (ID) ',
    'ZFA.7' : 'Opposition du patient à l’accès en mode centre de régulation (ID) ',
    'ZFA.8' : 'Date de recueil de l’état des oppositions du patient (TS) ',
    'ZFP': 'Situation professionnelle',
    'ZFP.1' : '/Activité Socioprofessionnelle (ID) ',
    'ZFP.2' : '/Catégorie Socioprofessionnelle (ID) ',
    'ZFV': 'Complément d’information sur la venue',
    'ZFV.1' : 'Etablissement de provenance (DLD) ',
    'ZFV.2' : 'Mode de Transport de Sortie (CE) ',
    'ZFV.3' : '/Type de préadmission (IS) ',
    'ZFV.4' : 'Date de début de placement (psy) (IS) ',
    'ZFV.5' : 'Date de fin de placement (psy) (IS) ',
    'ZFV.6' : 'Adresse de la provenance ou de la destination (XAD) ',
    'ZFV.7' : 'NDA de l\'établissement de provenance (CX) ',
    'ZFV.8' : 'Numéros d’archives ',
    'ZFV.9' : '/Mode de sortie personnalisé ',
    'ZFV.10' : 'Code RIM-P du mode légal de soin (CE) ',
    'ZFV.11' : 'Prise en charge durant le transport (CE) ',
    'ZFM': 'Mouvement PMSI',
    'ZFM.1' : '/Mode d’entrée PMSI (IS) ',
    'ZFM.2' : '/Mode de sortie PMSI (IS) ',
    'ZFM.3' : '/Mode de provenance PMSI (IS) ',
    'ZFM.4' : '/Mode de destination PMSI (IS) ',
    'ZFD': 'Complément démographique',
    'ZFD.1' : 'Date Lunaire (NA) ',
    'ZFD.2' : 'Nombre de semaines de gestation (NM) ',
    'ZFD.3' : 'Consentement SMS ',
    'ZFD.4' : '/Indicateur de date de naissance modifiée (IS) ',
    'ZFD.5' : '/Mode d’obtention de l’identité (IS) ',
    'ZFD.6' : 'Date d’interrogation du téléservice INSi (TS) ',
    'ZFD.7' : 'Justificatif d’identité (IS) ',
    'ZFD.8' : 'Date de fin de validité du justificatif d’identité (TS) ',
    'ZFS': 'Mode légal de soins en psychiatrie',
    'ZFS.1' : 'Set ID - ZFS ',
    'ZFS.2' : 'Identifiant du mode légal de soin ',
    'ZFS.3' : 'Date et heure du début du mode légal de soin ',
    'ZFS.4' : 'Date et heure du fin du mode légal de soin ',
    'ZFS.5' : 'Code action portant sur le mode légal de soin ',
    'ZFS.6' : 'Mode légal de soin ',
    'ZFS.7' : 'Code RIM-P du mode légal de soin ',
    'ZFS.8' : 'commentaires ',
    'OBX': 'Observation/Result',
    'OBX.1' : '/Set ID – OBX, Obligatoire ',
    'OBX.2' : '/Type de l’Observation, Obligatoire ',
    'OBX.3' : 'Identifiant de l’Observation, Obligatoire ',
    'OBX.4' : 'Observation Sub-ID',
    'OBX.5' : 'Observation Value',
    'OBX.6' : 'Unité, Conditionnel ',
    'OBX.7' : 'References Range',
    'OBX.8' : 'Abnormal Flags',
    'OBX.9' : 'Probability',
    'OBX.10' : 'Nature of Abnormal Test',
    'OBX.11' : '/Statut de l’observation ',
    'OBX.12' : 'Effective Date of Reference Range',
    'OBX.13' : 'User Defined Access Checks',
    'OBX.14' : 'Date et heure de l’observation ',
    'OBX.15' : 'Producer\'s ID',
    'OBX.16' : 'Responsable de l’observation ',
    'OBX.17' : 'Observation Method',
    'OBX.18' : 'Equipment Instance Identifier',
    'OBX.19' : 'Date/Time of the Analysis',
    
   // composants data type
    'CE.1': '/Identifier',
    'CE.2': '/Text',
    'CE.3': '/Name of Coding System',
    'CE.4': '/Alternate Identifier',
    'CE.5': '/Alternate Text',
    'CE.6': '/Name of Alternate Coding System',
    'CX.1' : '/Identifiant (ST)',
    'CX.2' : 'Check Digit',
    'CX.3' : 'Check Digit Scheme',
    'CX.4' : 'Autorité d’affectation (HD)',
    'CX.5' : '/Code de type d’identifiant (ID)',
    'CX.6' : 'Etablissement ou entité géographique (HD)',
    'CX.7' : '/Date effective (DT)',
    'CX.8' : 'Expiration Date',
    'CX.9' : '/Entité juridique (CWE)',
    'CX.10' : '/Service, Unité ou Département (CWE)',
    'MSG.1': '/Message Code',
    'MSG.2': '/Trigger Event',
    'MSG.3': '/Message Structure',
    'HD.1' : '/Namespace ID',
    'HD.2' : '/Universal ID',
    'HD.3' : '/Universal ID Type',
    'PL.1' : '/code de l’UF d’hébergement',
    'PL.2' : '/chambre',
    'PL.3' : '/lit',
    'PL.4' : 'établissement',
    'PL.5' : '/Location Status',
    'PL.6' : '/Person Location Type * (inutilisé)',
    'PL.7' : '/Building',
    'PL.8' : '/Floor',
    'PL.9' : '/Location Description',
    'PL.10' : '/Comprehensive Location Identifier',
    'PL.11' : '/Assigning Authority for Location',
    'XAD.1' : 'Voie de l’adresse (SAD)',
    'XAD.2' : '/Compléments d’adresse (ST)',
    'XAD.3' : '/Commune (ST)',
    'XAD.4' : '/Etat ou province (ST)',
    'XAD.5' : '/Code postal ou code zip (ST)',
    'XAD.6' : '/Pays (ID)',
    'XAD.7' : '/Type d’adresse (ID)',
    'XAD.8' : '/Other Geographic Designation',
    'XAD.9' : '/Cedex (IS)',
    'XAD.10' : '/Census Tract',
    'XAD.11' : '/Address Representation Code',
    'XAD.12' : '/Address Validity Range',
    'XAD.13' : '/Date de début de validité (TS)',
    'XAD.14' : '/Date de fin de validité (TS)',
    'SAD.1' : '/Ligne d’adresse',
    'SAD.2' : '/Street Name *',
    'SAD.3' : '/Dwelling Number *',
    'XCN.1' : '/Identifiant de la personne (ST)',
    'XCN.2' : 'Nom de famille (FN)',
    'XCN.3' : '/Premier prénom (ST)',
    'XCN.4' : '/Deuxième prénom et suivants (ST)',
    'XCN.5' : '/Suffix (e.g., JR or III) *',
    'XCN.6' : '/Préfixe (ST)',
    'XCN.7' : '/Degree (e.g., MD) *',
    'XCN.8' : '/Source Table *',
    'XCN.9' : 'Autorité d’affectation (HD)',
    'XCN.10' : '/Type de nom (ID)',
    'XCN.11' : '/Type d’identifiant (ID)',
    'XCN.12' : '/Check Digit Scheme',
    'XCN.13' : '/Identifier Type Code *',
    'XCN.14' : '/Assigning Facility',
    'XCN.15' : '/Name Representation Code *',
    'XCN.16' : '/Name Context *',
    'XCN.17' : '/Name Validity Range',
    'XCN.18' : '/Name Assembly Order *',
    'XCN.19' : '/Effective Date *',
    'XCN.20' : '/Expiration Date *',
    'XCN.21' : '/Professional Suffix *',
    'XCN.22' : '/Assigning Jurisdiction *',
    'XCN.23' : '/Assigning Agency or Department *',
    'XON.1' : '/Nom de l’organisation (ST)',
    'XON.2' : '/Organization Name Type Code *',
    'XON.3' : '/ID Number',
    'XON.4' : '/Check Digit',
    'XON.5' : '/Check Digit Scheme',
    'XON.6' : '/Autorité d’affectation de l’identifiant (HD)',
    'XON.7' : '/Type d’identifiant (ID)',
    'XON.8' : '/Assigning Facility',
    'XON.9' : '/Name Representation Code *',
    'XON.10' : '/Identifiant de l’organisation (ST)',
    'XPN.1' : 'Nom de famille (FN)',
    'XPN.2' : '/Premier prénom (ST)',
    'XPN.3' : '/Second prénoms et suivants (ST)',
    'XPN.4' : '/Suffix (e.g. JR or III) *',
    'XPN.5' : '/Préfixe – civilité (ST)',
    'XPN.6' : '/Degree (e.g., MD)',
    'XPN.7' : '/Type de nom (ID)',
    'XPN.8' : '/Name Representation Code *',
    'XPN.9' : '/Name Context *',
    'XPN.10' : '/Name Validity Range',
    'XPN.11' : '/Name Assembly Order *',
    'XPN.12' : '/Effective Date *',
    'XPN.13' : '/Expiration Date *',
    'XPN.14' : '/Professional Suffix *',
    'XTN.1' : '/Telephone Number *',
    'XTN.2' : '/type de numéro (ID)',
    'XTN.3' : '/type d’équipement (ID)',
    'XTN.4' : '/adresse e-mail (ST)',
    'XTN.5' : '/Country Code',
    'XTN.6' : '/Area/City Code *',
    'XTN.7' : '/Local Number *',
    'XTN.8' : '/Extension *',
    'XTN.9' : '/texte libre (ST)',
    'XTN.10' : '/Extension Prefix *',
    'XTN.11' : '/Speed Dial Code *',
    'XTN.12' : '/n° de téléphone non formaté (ST)',
    ] as Map
  
}
