package fr.gpmsi.da

import java.sql.ResultSet
import java.sql.PreparedStatement


/**
 * Définition d'une colonne de Données de type Char 
 */
class CChar extends ColumnDef {
    int maxlen
    CChar(String name, int maxlen) { setName(name) ; this.maxlen = maxlen }
    int getMaxLength() { return maxlen }
    
    boolean isAutogenerated() { return false }
    
    //produire une valeur correctement typee a partir du String fourni
    Object stringToValue(String str, DaPreferences prefs) {
        if (str == null || str == '') return null
        else {
            if (str.length() <= getMaxLength()) { return str }
            if (prefs.cutWhenOverflow) return str.substring(0, getMaxLength())
            else throw new MaximumSizeExceededException()
        }
    }
    
    //produire une String a partir de la valeur fournie
    String valueToString(Object val, DaPreferences prefs) {
      if (val == null) return '' else return val.toString()
    }

    /** attribuer la valeur dans le PreparedStatement  (y compris le type correct pour setNull) */
    void setPsValue(PreparedStatement ps, int index, Object val) {
        if (val == null) ps.setNull(index, Types.VARCHAR)
        else ps.setString(index, val as String);
    }
    
    /** Prendre la valeur dans le ResultSet */
    Object getRsValue(ResultSet rs, int index) {
        return rs.getString(index)
    }

}