package fr.gpmsi.da

import java.util.Date

import groovy.transform.EqualsAndHashCode

import java.sql.ResultSet
import java.sql.Time
import java.sql.Types
import java.sql.PreparedStatement
import java.text.ParseException
import java.text.SimpleDateFormat
import java.text.DateFormat

/**
 * Définition d'une colonne de type de donnee Time, pour pouvoir stocker un type de donnée TIME en base H2
 */
@EqualsAndHashCode(callSuper = true)
class CTime extends ColumnDef {
    static SimpleDateFormat isoSdf = new SimpleDateFormat('HH-mm-ss.SSS')
    DateFormat df = isoSdf
    private int precision = 0

    /**
     * Construire un objet Time de la façon appropriée, c'est à dire en utilisant un Calendar obtenu via getInstance().
     * Cela construit un objet Time correct par rapport à la Timezone du système.
     * @param hours heures dans la timezone du système
     * @param minutes minutes dans la timezone du système
     * @param seconds secondes dans la timezone du système
     * @param milliseconds millisecondes dans la timezone du système
     * @return un objet Time avec la bonne valeur UTC
     */
    static Time makeTime(int hours, int minutes, int seconds, int milliseconds) {
      Calendar cal = Calendar.getInstance()
      cal.clear()
      cal.set(1970, 0, 1, hours, minutes, seconds)
      cal.set(Calendar.MILLISECOND, milliseconds)
      return new Time(cal.getTimeInMillis())
    }
    
    /**
     * La colonne est-elle autogénérée ?
     * @return toujours false
     */
    boolean isAutogenerated() { return false }
    
    /**
     * Constructeur à partir du nom
     * @param name le nom
     */
    CTime(String name) { setName(name); setSqlType(Types.TIME) }
    
    /**
     * Constructeur avec nom et format
     * @param name Le nom 
     * @param df Le format d'heure
     */
    CTime(String name, DateFormat df) { setName(name) ; this.df = df; setSqlType(Types.TIME) }
    
    /**
     * Définir le format de date
     * @param df le format de date
     * @return this
     */
    CTime setDateFormat(DateFormat df) { this.df = df; return this }
    
    /**
     * Retourner la longueur maximum
     * @return toujours 0
     */
    int getMaxLength() { return 0 }
    
    /**
     * produire une donnee correctement typee a partir de la String donnee
     * @param str La String qui représente la donnée
     * @param prefs Les préférences de data access, peut être null
     * @return un Objet produit à partir de la String
     */
    Object stringToValue(String str, DaPreferences prefs) {
        if (str == null || str.trim() == "") return null
        if (df != null) {
            try {
                return new java.sql.Time(df.parse(str).getTime()) //use supplied DateFormat
            }
            catch (ParseException pex3) {
                if (prefs?.illegalDatesToNull) return null 
                else throw new Exception("original String '$str'", pex3)
            }
        }
    }
    
    /**
     * Retourner une String a partir de la valeur fournie
     * @param val la valeur à convertir
     * @param prefs les préférences data access, peut être null
     * @return une String qui représente l'objet 
     */
    String valueToString(Object val, DaPreferences prefs) {
        if (val == null) return ""
        return df.format(val)
    }

    /**
     * attribuer la valeur dans le PreparedStatement  (y compris le type correct pour setNull). Accepte java.util.Date ou java.sql.Date
     * @param ps Le prepared statement à remplir
     * @param index Le numéro de paramètre à remplir (commence à 1)
     * @param val La valeur, seuls sont pris en charge java.util.Date et java.sql.Time
     */
    //TODO prendre en charge aussi les nouveaux types de données temporelles
    void setPsValue(PreparedStatement ps, int index, Object val) {
        if (val == null) ps.setNull(index, Types.TIME)
        else {
            if (val instanceof java.sql.Time) ps.setTime(index, val as java.sql.Time)
            else if (val instanceof java.util.Date) {
                java.util.Date d1 = val as java.util.Date
                java.sql.Time t1 = new java.sql.Time(d1.getTime())
                ps.setTime(index, t1)
            }
            else throw new IllegalArgumentException("Type de valeur non pris en charge : " + val.class.name)
        }
    }
    
    /**
     * Prendre la valeur dans le ResultSet
     * @param rs le ResultSet
     * @param index le numéro dans le ResultSet (commence à 1)
     * @return l'objet résultat
     */
    Object getRsValue(ResultSet rs, int index) {
        return rs.getDate(index)
    }
    
    /**
     * Prendre le DDL qui représente cette colonne
     * @param dialect Le nom du dialecte pris en charge. Actuellement seul H2 est supporté
     * @return Une String qui contient du DDL qui représente la déclaration de cette colonne
     */
    String getDdl(String dialect) {
      if (dialect.equalsIgnoreCase("H2")) {
        String prec = precision > 0 ? "($precision)" : ''
        if (extraDdl) return "$name TIME$prec $extraDdl"
        else return "$name TIME$prec"
      }
      else return "Dialecte non pris en charge : $dialect"
    }

    /**
     * Précision utilisé au delà des secondes (nombre de décimales de millisecondes, 0 à 3). Par défaut à 0.
     * @return La précision
     */
    public int getPrecision() {
      return precision;
    }

    /**
     * Attribuer la précision utilisé au delà des secondes (nombre de décimales de millisecondes, 0 à 3). Par défaut à 0.
     * @param precision La précision
     */
    public void setPrecision(int precision) {
      this.precision = precision;
    }

}

