package fr.gpmsi.da

import java.sql.ResultSet
import java.sql.PreparedStatement

/**
 * Définition d'une colonne de type Varchar
 */
class CVarchar extends ColumnDef {
  int maxlen;

  boolean isAutogenerated() { return false }

  CVarchar(String name, int maxlen) {
    setName(name)
    this.maxlen = maxlen
  }

  int getMaxLength() { return maxlen; }

  //make a correctly typed value from the given String.
  //if str is empty string, returns null
  Object stringToValue(String str, DaPreferences prefs) {
      if (str == '' || str == null) return null
      else  {
          if (str.length() <= getMaxLength()) { return str }
          if (prefs.cutWhenOverflow) return str.substring(0, getMaxLength())
          else throw new MaximumSizeExceededException()
      }
  }

  //make a String from the given value. If val is null, returns the empty string
  String valueToString(Object val, DaPreferences prefs) { 
      if (val == null) return '' else return val.toString() 
  } 

  /** Set value in PreparedStatement (including correct type for setNull) */
  void setPsValue(PreparedStatement ps, int index, Object val) {
      if (val == null) ps.setNull(index, Types.VARCHAR)
      else ps.setString(index, val as String);
  }
  
  /** Get value from ResultSet */
  Object getRsValue(ResultSet rs, int index) {
      return rs.getString(index)
  }

}